# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6WglAYAd9fykf_6cSy2t2C_qYKdeoVI
"""

!git clone https://github.com/ultralytics/yolov3

import time
import glob
import torch
import os

from IPython.display import Image, clear_output 
print('PyTorch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

from google.colab import drive
drive.mount('/content/drive')

!ln -s /content/drive/My\ Drive/ /mydrive
!ls /mydrive

!unzip /mydrive/Yolov3/Images.zip -d data/

!mv "./data/Images" "./coco/"

!cp /mydrive/Yolov3/yolov3.cfg ./yolov3/cfg/

!cp /mydrive/Yolov3/coco1cls.txt ./yolov3/data
!cp /mydrive/Yolov3/coco1cls.data ./yolov3/data
!cp /mydrive/Yolov3/coco.names ./yolov3/data

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov3
!python3 train.py --data data/coco1cls.data --cfg cfg/yolov3.cfg --weights '' --batch-size 8 --epochs 20

!mv "/content/yolov3/weights/best.pt" "/content/drive/My Drive/Yolov3/"

!mv "/content/yolov3/weights/last.pt" "/content/drive/My Drive/Yolov3/"